[TRL_SFT_Trainer] Fix and Update Examples code (#1161)
SUMMARY:
* Fix examples script failure
https://github.com/neuralmagic/llm-compressor-testing/actions/runs/13350457472/job/37286313648

PROBLEM
1. 
```bash
 cpy 2 '/home/gohashi/llm-compressor/examples/trl_mixin/ex_trl_constant.py'
...
TypeError: SessionManagerMixIn.__init__() missing 2 required positional arguments: 'data_args' and 'model_args'

```

2.
```bash
(.venv) gohashi@janice:~/llm-compressor$ cpy 2 '/home/gohashi/llm-compressor/examples/trl_mixin/ex_trl_constant.py'
...
TypeError: SFTTrainer.__init__() got an unexpected keyword argument 'max_seq_length'
```

3.
```bash
(.venv) gohashi@janice:~/llm-compressor$ cpy 2 '/home/gohashi/llm-compressor/examples/trl_mixin/ex_trl_constant.py'
...
AttributeError: 'NoneType' object has no attribute 'save_compressed'
```

4.
```
(.venv) gohashi@janice:~/llm-compressor$ cpy 2 '/home/gohashi/llm-compressor/examples/trl_mixin/ex_trl_constant.py'
...
/home/gohashi/llm-compressor/src/llmcompressor/transformers/finetune/session_mixin.py:97: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
...
```


SOLUTION:
1. Caused by
https://github.com/vllm-project/llm-compressor/pull/1103/files#diff-059b8cf7e48691cd2d5ddda1d0ba5f584657a70c5804797d38c902b433777335R69-R70,
where `model_args` and `data_args` is required. Add it to the code and
make `model_args` and `data_args` optional
2. `max_seq_length` is not a part of `TrainingArgs`, which gets called
by super first. We see that it is used in `SFTConfig` that inherits
`TRLSFTConfig` where `max_seq_length` is used. `TRLSFTConfig` inherits
`TrainingArguments` to modify the code.
3. Make `model_args` required
4. Bug warning. Update `tokenizer` to `processing_class`

TEST PLAN:
*
Pass`[examples/trl_mixin/ex_trl_constant.py](https://github.com/vllm-project/llm-compressor/compare/sessionmixin-revert-signature?expand=1#diff-f14ef5a7e5c54f35e347fd75ed37e39b8f6db081199bd6233cf14d2c1b4bdef9)`
* Pass existing tests