[tests] switch lm_eval invocation to use pre-loaded transformers model (#2018)
SUMMARY:
`lm_eval==0.4.9.1` has a broken entrypoint when using a model with a
compressed-tensors quantization config with `--model hf`:

```
FAILED tests/lmeval/test_lmeval.py::TestLMEval::test_lm_eval[tests/lmeval/configs/vl_w4a16_actorder_weight.yaml] - ValueError: The model is quantized with CompressedTensorsConfig but you are passing a dict config. Please make sure to pass the same quantization config class to `from_pretrained` with different loading attributes.
```

It has been resolved on main, though a separate issue persists that is
resolved with this PR --
https://github.com/EleutherAI/lm-evaluation-harness/pull/3393.

While that is in transit, and to avoid having to use lm_eval main in our
ci/cd, this PR resolves the issue by pre-loading the model with
`AutoModelForCausalLM` rather than relying on lm_eval's strange model
loading logic.


TEST PLAN:
tests run now, for some reason the vl test is super slow on ibm-h100-1.
The same thing happens on main. I've seen this before, but I'm not sure
what's causing it. It seemed to correct itself the following day

---------

Signed-off-by: Brian Dellabetta <bdellabe@redhat.com>