[Tracing] Better runtime error messages (#1307)
## Purpose ##
* Add better exception messages when encountering tracing errors

## Example ##
* Below is an example of a potential tracing runtime error (this
particular error was forced for demonstration purposes)
````
Traceback (most recent call last):
  File "/home/kyle/llm-compressor/src/llmcompressor/pipelines/sequential/helpers.py", line 45, in forward
    outputs = forward_fn(*args, **kwargs)
  File "<string>", line 12, in forward
TypeError: iter(v, w): v must be callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kyle/llm-compressor/src/llmcompressor/modifiers/quantization/gptq/base.py", line 234, in on_initialize
    run_sequential(
  File "/home/kyle/llm-compressor/src/llmcompressor/pipelines/sequential/pipeline.py", line 67, in run_pipeline
    subgraph.forward(model, **inputs)
  File "/home/kyle/llm-compressor/src/llmcompressor/pipelines/sequential/helpers.py", line 47, in forward
    raise RuntimeError(
RuntimeError: Raised an exception during execution of the following code:
```
1
2
3
4 def forward(self, input_ids : torch.Tensor, attention_mask :
torch.Tensor):
5     model_rotary_emb_inv_freq = self.model.rotary_emb.inv_freq
6 getitem_10 = model_rotary_emb_inv_freq[(None, slice(None, None, None),
None)]; model_rotary_emb_inv_freq = None
7 model_embed_tokens = self.model.embed_tokens(input_ids); input_ids =
None
8     size_3 = attention_mask.size();  size_3 = None
9     dim = attention_mask.dim()
10     size_6 = attention_mask.size()
11 getitem_8 = attention_mask[(slice(None, None, None), None, None,
slice(None, None, None))]
12     iter_6 = iter(attention_mask, 'device');  attention_mask = None
13     float_1 = getitem_10.float();  getitem_10 = None
14     size = model_embed_tokens.size()
15     iter_1 = iter(model_embed_tokens, 'device')

```
````

## Changes ##
* Move forward call to inside Subgraph class and wrap forward call in
order to catch and propagate exceptions

---------

Signed-off-by: Kyle Sayers <kylesayrs@gmail.com>
Signed-off-by: Kelvin Cheng <kelvincheng216@gmail.com>