[Tests] Increase max seq length for tracing tests (#1478)
## Purpose ##
* Support `transformers>=4.52`

## Background ##
* After`transformers>=4.50`, many multimodal processors now check that
image tokens have not been truncated during the tokenization process.
Previously we were tracing with samples which truncated image tokens,
leading to technically invalid samples. This doesn't matter for tracing,
but does make sense for transformers to check.

```
ValueError: Mismatch in `image` token count between text and `input_ids`. Got ids=[354] and text=[2197]. Likely due to `truncation='max_length'`. Please disable truncation or increase `max_length`.
```

## Changes ##
* Increase the `max_seq_length` for tracing tests

Signed-off-by: Kyle Sayers <kylesayrs@gmail.com>