[BugFix] TRL distillation bug fix (#1278)
SUMMARY:
Bug fix for 
```
0/test_example_scripts_ex_trl_co0/examples/trl_mixin/sft_trainer.py", line 15, in _init\n    super().init(*args, **kwargs)\nTypeError: SessionManagerMixIn.init_() missing 1 required positional argument: \'dataset_args\'\n').returncode
```
Solution is to revert the dataset args to optional back again


TEST PLAN:
Pass script run

Co-authored-by: Dipika Sikka <dipikasikka1@gmail.com>