[Autowrapper] Support Gemma3n, autowrapper improvements (#1693)
## Purpose ##
* Support Gemma3 and models which have similar implementations in their
model definitions
* Resolves #1711
* Add better debugging messages when failures happen inside autowrapped
code

```
  File "/home/kylesayrs/llm-compressor/src/llmcompressor/pipelines/sequential/ast_helpers.py", line 105, in append_autowrap_source_on_fail
    raise RuntimeError(message) from exception
RuntimeError: name 'explode_the_bomb' is not defined


--- <Autowrapped LlamaModel 140503462592384>:43 ---
 ...

@torch.fx.wrap
def wrapped_1(input_ids, inputs_embeds):
    if inputs_embeds is None:
        inputs_embeds: torch.Tensor = self.embed_tokens(input_ids)
    return (inputs_embeds,)

@torch.fx.wrap
def wrapped_0(input_ids, inputs_embeds):
    if (input_ids is None) ^ (inputs_embeds is not None):
        raise ValueError('You must specify exactly one of input_ids or inputs_embeds')
    return ()

def forward(self, input_ids: Optional[torch.LongTensor]=None, attention_mask: Optional[torch.Tensor]=None, position_ids: Optional[torch.LongTensor]=None, past_key_values: Optional[Cache]=None, inputs_embeds: Optional[torch.FloatTensor]=None, cache_position: Optional[torch.LongTensor]=None, use_cache: Optional[bool]=None, **kwargs: Unpack[TransformersKwargs]) -> BaseModelOutputWithPast:
    () = wrapped_0(input_ids, inputs_embeds)
    inputs_embeds, = wrapped_1(input_ids, inputs_embeds)
    past_key_values, = wrapped_2(past_key_values, use_cache)
    cache_position, past_seen_tokens = wrapped_3(cache_position, inputs_embeds, past_key_values)
    position_ids, = wrapped_4(cache_position, position_ids)
>   explode_the_bomb()
    causal_mask = wrapped_5(attention_mask, cache_position, inputs_embeds, past_key_values, position_ids)
    hidden_states = inputs_embeds
    position_embeddings = self.rotary_emb(hidden_states, position_ids)
    for decoder_layer in self.layers[:self.config.num_hidden_layers]:
        hidden_states = decoder_layer(hidden_states, attention_mask=causal_mask, position_ids=position_ids, past_key_values=past_key_values, cache_position=cache_position, position_embeddings=position_embeddings, **kwargs)
    hidden_states = self.norm(hidden_states)
    return BaseModelOutputWithPast(last_hidden_state=hidden_states, past_key_values=past_key_values)
```

## Changes ##
* Handle source code which uses the walrus operator within if statements
* Do not attempt to statically evaluate conditions containing walrus
operators, as this is the only case where an if statement has a
necessary side-effect (the declaration of a new variable)
* Account for walrus operators when tracking names, similar to
https://github.com/vllm-project/llm-compressor/pull/1616
* Previously, all function decorators were removed from definitions.
However, HF uses some function wrappers which have very subtle effects
on kwarg passing such as `can_return_tuple`. These decorators must be
kept
* Improve debugging for autowrapped code
* Fix tracebacks, now failures within autowrapped code will include
which line they failed on
* Add util function `append_autowrap_source_on_fail` which appends the
entire autowrapped source upon fail
* Add `project_per_layer_inputs` to list of ignored functions for
tracing

## Testing ##
* Added gemma3n text and vision tests
* Added walrus operator test to autowrapping tests

---------

Signed-off-by: Kyle Sayers <kylesayrs@gmail.com>
Co-authored-by: Dipika Sikka <dipikasikka1@gmail.com>