Fix versioning for source installs (#1370)
SUMMARY:
Update the various source installs in testing workflows to properly
fetch git tags and set the `BUILD_TYPE` to nightly. This notably results
in installing a nightly-style version of `compressed-tensors` for the
source install to allow it to satisfy the version requirements from
`llm-compressor`.

TEST PLAN:
Prior to these changes, you would find a broken `llm-compressor` version
in the local install, as well as a warning about the source install
version of `compressed-tensors` being incompatible:

```
Successfully installed […] llmcompressor-0.1.dev1+g67614d5 […]
...
Installing collected packages: compressed-tensors
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
llmcompressor 0.1.dev1+g8ca8fd3 requires compressed-tensors>=0.9.4a2, but you have compressed-tensors 0.1.dev1+g16e6435 which is incompatible.
Successfully installed compressed-tensors-0.1.dev1+g16e6435
```

With the changes, both packages have proper versioning and no
compatibility complaints:

```
Successfully installed […] llmcompressor-0.5.1.dev28+g3b1aac94 […]
...
Installing collected packages: compressed-tensors
Successfully installed compressed-tensors-0.9.4a20250421
```

---------

Signed-off-by: Domenic Barbuzzi <dbarbuzz@redhat.com>