[bugfix] saving model without model.name_or_path (#2061)
Summary:

the way models were saved assumed that model.name_or_path was populated
but this is not always the case. I think that if you generate a model
and then immediately quantize it, you'll run into this problem.

This PR relaxes this assumption so that the model can be saved.

TEST PLAN:
ran https://gist.github.com/HDCharles/78c55da388076aa046ee893edfbd9df5

previously you'd get:

huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric
chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and
the maximum length is 96: ''.

now:

no error

---------

Signed-off-by: HDCharles <charlesdavidhernandez@gmail.com>