Use natural sort for ordered grouping by layer (#2175)
SUMMARY:
The current code is implicitly relying on ordered grouping by layer
however that is not always the case in practice and also since the API
contract allows sets explicitly. When the order is broken it leads to:

ValueError: Matched a re:.*mlp\.gate_proj\.weight$ twice before
completing set (language_model.model.layers.12.mlp.gate_proj.weight,
language_model.model.layers.4.mlp.gate_proj.weight)

TEST PLAN:
The https://huggingface.co/mistralai/Ministral-3-14B-Reasoning-2512 can
be used to test this and is a real life example on which the ValueError
above has tripped.

---------

Signed-off-by: Anton Bobrov <antbob@users.noreply.github.com>
Signed-off-by: Anton Bobrov <8211973+antbob@users.noreply.github.com>
Co-authored-by: Anton Bobrov <antbob@users.noreply.github.com>
Co-authored-by: gemini-code-assist[bot] <176961590+gemini-code-assist[bot]@users.noreply.github.com>
Co-authored-by: Dipika Sikka <dipikasikka1@gmail.com>