[GPTQ] Fix FP8 handling on A100 and disable failing tests on A100 (#3181)
## Summary
https://github.com/vllm-project/llm-compressor/pull/3128 made it so that
fp8 quant on A100 fails since triton doesn't support the necessary cast
on A100 and added tests that do NVFP4 on A100 (also fail)

- require compute capability 9.0 for GPTQ FP8 and FP8-scale NVFP4 test
cases
- fix triton kernel to use a supported fp8 cast in triton instead

## Testing

(on A100)

`pytest -vs -rs tests/llmcompressor -k gptq`

PR
```
==== 99 passed, 1 skipped, 682 deselected, 29 warnings in 85.54s (0:01:25) =====
```

main
```
FAILED tests/llmcompressor/modifiers/gptq/test_gptq_quantize.py::test_fused_gptq_kernel_matches_eager[None-fp8-channel]
FAILED tests/llmcompressor/modifiers/gptq/test_gptq_quantize.py::test_fused_gptq_kernel_matches_eager[None-fp8-block]
FAILED tests/llmcompressor/modifiers/gptq/test_gptq_quantize.py::test_fused_gptq_kernel_matches_eager[weight-fp8-channel]
FAILED tests/llmcompressor/modifiers/gptq/test_gptq_quantize.py::test_fused_gptq_kernel_matches_eager[weight-fp8-block]
FAILED tests/llmcompressor/transformers/gptq/test_gptq_oneshot.py::test_oneshot_application[recipe7]
FAILED tests/llmcompressor/transformers/gptq/test_gptq_oneshot.py::test_oneshot_application[recipe8]
= 6 failed, 93 passed, 1 skipped, 689 deselected, 27 warnings in 101.77s (0:01:41) =
```

---------

Signed-off-by: HDCharles <charlesdavidhernandez@gmail.com>
Co-authored-by: HDCharles <{"message":"Not Found","documentation_url":"https://docs.github.com/rest/users/emails#list-email-addresses-for-the-authenticated-user","status":"404"}>